<template>
  <div class="container">
    <div class="row">
      <div>
        <h1>ReFair App</h1>
        <!-- Contenuto Capitolo 1 -->
        <div class="content">
          <!-- Il contenuto principale rimane lo stesso -->

          <div id="chapter1">
            <h2>CAPITOLO 1</h2>
            <div class="alert alert-info fade show" role="alert">
              <strong>Info!</strong> To properly run the <b>ReFair</b> analysis,
              you should upload an xlsx file called "stories.xlsx".
              <hr />
              The spreadsheet must contain only a single column called 'User
              Story' with all user stories to be analysed.
              <ul>
                <li>
                  The <strong> Load </strong> Button allows you to upload the
                  user stories spreadsheet;
                </li>
                <li>
                  The <strong> Report </strong> Button allows you to download a
                  structured JSON report with the user stories analysed by
                  ReFair;
                </li>
                <li>
                  After the stories uploading, the
                  <strong> Analyze </strong> Button allows you to visualize the
                  ReFair analysis with respect to a single user story.
                </li>
              </ul>
            </div>

            <div
              class="btn-toolbar mb-3 justify-content-between"
              role="toolbar"
              aria-label="Toolbar with button groups"
            >
              <div class="file-upload">
                <input
                  type="file"
                  id="file"
                  class="form-control"
                  @change="handleStoriesUpload($event)"
                />
                <!---->
                <button type="button" class="button select">
                  <label for="file" class="button__text"> Select file </label>
                  <span class="button__icon"
                    ><ion-icon name="document-attach-outline"></ion-icon
                  ></span>
                </button>
                <!---->
                <span id="file-name" class="file-name">No file Selected</span>
              </div>
              <div>
                <button
                  v-on:click="submitFile()"
                  type="button"
                  class="button load"
                  style="margin-right: 20px"
                >
                  <span class="button__text">Load</span>
                  <span class="button__icon"
                    ><ion-icon name="cloud-upload-outline"></ion-icon
                  ></span>
                </button>
                <button
                  v-on:click="reportStories()"
                  type="button"
                  class="button report"
                  id="report"
                >
                  <span class="button__text">Report</span>
                  <span class="button__icon"
                    ><ion-icon name="code-slash-outline"></ion-icon
                  ></span>
                </button>
              </div>
            </div>
          </div>

          <!-- Contenuto Capitolo 2 -->
          <div id="chapter2">
            <h2>CAPITOLO 2</h2>
            <table class="table table-hover">
              <thead>
                <tr>
                  <th scope="col">User Stories</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="(story, index) in stories" :key="index">
                  <td>{{ story }}</td>
                  <td>
                    <div>
                      <button
                        type="button"
                        class="button analyze"
                        @click="toggleAnalyzeStoryModal(story)"
                      >
                        <span class="button__text">Analyze</span>
                        <span class="button__icon"
                          ><ion-icon name="analytics-outline"></ion-icon
                        ></span>
                      </button>
                    </div>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>

          <!-- Contenuto Capitolo 3 -->
          <div id="chapter3">
            <h2>CAPITOLO 3</h2>
            <p>
              In this section, you'll find detailed information about the
              analysis and reports generated by ReFair.
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Capitoli di navigazione -->
    <div class="sidebar">
      <div
        class="indicator"
        :style="{ transform: `translateY(${indicatorPosition}px)` }"
      ></div>
      <ChapterButton
        btnClass="btn_chapter"
        dataChapter="chapter1"
        buttonText="CAPITOLO 1"
        chapterId="chapter1"
        @scrollToChapter="scrollToChapter"
      />
      <ChapterButton
        btnClass="btn_chapter"
        dataChapter="chapter2"
        buttonText="CAPITOLO 2"
        chapterId="chapter2"
        @scrollToChapter="scrollToChapter"
      />
      <ChapterButton
        btnClass="btn_chapter"
        dataChapter="chapter3"
        buttonText="CAPITOLO 3"
        chapterId="chapter3"
        @scrollToChapter="scrollToChapter"
      />
    </div>

    <!-- analyze Story Modal -->
    <div
      ref="analyzeStoryModal"
      class="modal fade"
      :class="{
        show: activeAnalyzeStoryModal,
        'd-block': activeAnalyzeStoryModal,
      }"
      tabindex="-1"
      role="dialog"
    >
      <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">Story Details</h5>
            <div>
              <button
                type="button"
                class="button close"
                data-dismiss="modal"
                @click="closeAnalyzeStoryModal"
                style="margin-right: 10px"
              >
                <span class="button__text">Close</span>
                <span class="button__icon"
                  ><ion-icon name="close-circle-outline"></ion-icon
                ></span>
              </button>
              <button
                v-on:click="reportStory()"
                type="button"
                class="button report"
                id="report"
              >
                <span class="button__text">Report</span>
                <span class="button__icon"
                  ><ion-icon name="code-slash-outline"></ion-icon
                ></span>
              </button>
            </div>
          </div>
          <div class="modal-body">
            <p class="pt-3 mx-4"><b>User Story: </b> {{ story }}</p>
            <p class="pt-3 mx-4"><b>Story Domain: </b> {{ story_domain }}</p>
            <div class="pt-3 mx-4">
              <b>Story Tasks</b>
              <hr />
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col">Task</th>
                    <th scope="col">Sensitive Features</th>
                  </tr>
                </thead>
                <tbody>
                  <tr v-for="(features, task) in story_tasks" :key="task">
                    <td>{{ task }}</td>
                    <td>{{ features.toString().replaceAll(",", " - ") }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div
              v-if="
                series[0]['data'].length != null &&
                series[0]['data'].length > 0 != []
              "
              class="pt-3 mx-4"
            >
              <apexchart
                width="1000"
                type="bar"
                :options="options"
                :series="series"
              ></apexchart>
            </div>
            <div v-else class="pt-3 mx-4">No sensitive features suggested</div>
          </div>
          <div class="modal-footer"></div>
        </div>
      </div>
    </div>

    <div v-if="activeAnalyzeStoryModal" class="modal-backdrop fade show"></div>
  </div>
</template>

<script>
import axios from "axios";
import downloadjs from "downloadjs";
import VueApexCharts from "vue-apexcharts";

import ChapterButton from "./ChapterButton.vue";

const server = "http://localhost:5001";

export default {
  components: {
    ChapterButton,
  },
  data() {
    return {
      activeAnalyzeStoryModal: false,
      story: "",
      story_domain: "",
      story_tasks: [],
      stories: [],
      file: "",
      options: {
        chart: {
          id: "vuechart-example",
        },
        xaxis: {
          categories: [],
        },
      },
      series: [
        {
          name: "series-1",
          data: [],
        },
      ],
      activeButton: null, // Nuova proprietà per tracciare il pulsante attivo
      indicatorPosition: 0, // Posizione della linea
    };
  },
  methods: {
    handleStoriesUpload(event) {
      this.file = event.target.files[0];
    },

    reportStories() {
      let formData = new FormData();
      console.log(this.stories);
      formData.append("stories", JSON.stringify(this.stories));

      axios
        .post(server + "/reportStories", formData, {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        })
        .then((res) => {
          console.log(res.data);
          downloadjs(
            ("" + res.data).replaceAll("'", '"'),
            "report.json",
            "application/json"
          );
        })
        .catch((error) => {
          console.log(error);
        });
    },

    reportStory() {
      let formData = new FormData();
      console.log(this.story);
      formData.append("story", JSON.stringify(this.story));

      axios
        .post(server + "/reportStory", formData, {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        })
        .then((res) => {
          console.log(res.data);
          downloadjs(
            ("" + res.data).replaceAll("'", '"'),
            "report-" + this.story + ".json",
            "application/json"
          );
        })
        .catch((error) => {
          console.log(error);
        });
    },

    submitFile() {
      let formData = new FormData();
      formData.append("stories", this.file);

      axios
        .post(server + "/storiesload", formData, {
          headers: {
            "Content-Type": "multipart/form-data",
          },
        })
        .then((res) => {
          if (typeof res.data.stories === "undefined") {
            alert(res.data.motivation);
            this.stories = [];
          } else {
            const reportBtn = document.querySelector("#report");
            reportBtn.classList.remove("disabled");
            this.stories = res.data.stories;
          }
        })
        .catch(() => {
          this.stories = [];
        });
    },

    toggleAnalyzeStoryModal(story) {
      if (story) {
        this.story = story;
        let formData = new FormData();
        formData.append("story", this.story);

        axios
          .post(server + "/analyzeStory", formData, {
            headers: {
              "Content-Type": "multipart/form-data",
            },
          })
          .then((res) => {
            this.story_domain = res.data.domain;
            this.story_tasks = res.data.tasks_features;

            console.log(this.story_tasks);
            const body = document.querySelector("body");
            this.activeAnalyzeStoryModal = !this.activeAnalyzeStoryModal;

            var data = [];

            Object.keys(res.data.features_counts).forEach(function (key) {
              data.push({
                x: key,
                y: [res.data.features_counts[key]],
              });
            });

            if (this.activeAnalyzeStoryModal) {
              this.series = [
                {
                  name: "occurrencies",
                  data: data,
                },
              ];
              console.log(this.series[0]["data"]);
              body.classList.add("modal-open");
            } else {
              body.classList.remove("modal-open");
            }
          })
          .catch((error) => {
            console.error(error);
          });
      }
    },

    closeAnalyzeStoryModal() {
      const body = document.querySelector("body");
      this.activeAnalyzeStoryModal = !this.activeAnalyzeStoryModal;
      body.classList.remove("modal-open");
    },

    //Scripts related to the chapters section

    scrollToChapter(chapterId) {
      const button = this.$el.querySelector(`[data-chapter="${chapterId}"]`);
      this.activeButton = button; // Updates the active button
      this.updateIndicator(); // Update the indicator position

      document.getElementById(chapterId).scrollIntoView({ behavior: "smooth" });
    },

    updateIndicator() {
      if (!this.activeButton) return;
      const buttonRect = this.activeButton.getBoundingClientRect();
      const sidebarRect = this.$el
        .querySelector(".sidebar")
        .getBoundingClientRect();
      const indicatorY = buttonRect.top - sidebarRect.top;

      this.indicatorPosition = indicatorY; // Updates the position of the line
    },
  },

  mounted() {
    this.$nextTick(() => {
      this.activeButton = this.$el.querySelector(".btn_chapter"); // Initializes the first button as active
      this.updateIndicator(); // Sets up the starting position of the indicator
    });
  },
};

//Function needed to show the loaded file name
function handleStoriesUpload(event) {
  const fileInput = event.target;
  const fileNameElement = document.getElementById("file-name");
  const file = fileInput.files[0];

  if (file) {
    fileNameElement.textContent = file.name;
  } else {
    fileNameElement.textContent = "No file selected";
  }
}

// Assicurati che il DOM sia caricato prima di aggiungere l'evento
document.addEventListener("DOMContentLoaded", () => {
  const fileInput = document.querySelector(".form-control");
  fileInput.addEventListener("change", handleStoriesUpload);
});
</script>
